/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestCasesIndexRouteImport } from './routes/testCases/index'
import { Route as ConfigurationIndexRouteImport } from './routes/configuration/index'
import { Route as TestCasesAddTestCaseRouteImport } from './routes/testCases/addTestCase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesIndexRoute = TestCasesIndexRouteImport.update({
  id: '/testCases/',
  path: '/testCases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationIndexRoute = ConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesAddTestCaseRoute = TestCasesAddTestCaseRouteImport.update({
  id: '/testCases/addTestCase',
  path: '/testCases/addTestCase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testCases/addTestCase': typeof TestCasesAddTestCaseRoute
  '/configuration': typeof ConfigurationIndexRoute
  '/testCases': typeof TestCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testCases/addTestCase': typeof TestCasesAddTestCaseRoute
  '/configuration': typeof ConfigurationIndexRoute
  '/testCases': typeof TestCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testCases/addTestCase': typeof TestCasesAddTestCaseRoute
  '/configuration/': typeof ConfigurationIndexRoute
  '/testCases/': typeof TestCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testCases/addTestCase' | '/configuration' | '/testCases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testCases/addTestCase' | '/configuration' | '/testCases'
  id:
    | '__root__'
    | '/'
    | '/testCases/addTestCase'
    | '/configuration/'
    | '/testCases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestCasesAddTestCaseRoute: typeof TestCasesAddTestCaseRoute
  ConfigurationIndexRoute: typeof ConfigurationIndexRoute
  TestCasesIndexRoute: typeof TestCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testCases/': {
      id: '/testCases/'
      path: '/testCases'
      fullPath: '/testCases'
      preLoaderRoute: typeof TestCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/': {
      id: '/configuration/'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testCases/addTestCase': {
      id: '/testCases/addTestCase'
      path: '/testCases/addTestCase'
      fullPath: '/testCases/addTestCase'
      preLoaderRoute: typeof TestCasesAddTestCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestCasesAddTestCaseRoute: TestCasesAddTestCaseRoute,
  ConfigurationIndexRoute: ConfigurationIndexRoute,
  TestCasesIndexRoute: TestCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
